### PR TITLE
Added support for managing .P12 certificates

### PR DESCRIPTION
**Pull request by Mharlin**

### CODE REVIEW

**Comment by ffrank** [comment]
Ping @stack72

**Comment by daenney** [comment]
@ffrank This looks fine to me. Lets just merge it?

**Comment by ffrank** [comment]
Eh, sure. What's the worst that can happen? :)

Thanks @Mharlin !

**Comment by liamjbennett** [comment]
+1 from me. Also lost my commit bit here.

**Comment by daenney** [comment]
@ffrank and @liamjbennett: Sorry about that. We've been really bad at moving people back out of the modules/admin team once modules have been transferred and adding collaborators with write access to the module instead. I just fixed the latter so you're good to go again.

**Comment by ffrank** [comment]
Awesome. Thanks!

**Pull request merged**
